name: Build Android APK
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Godot
      run: |
        wget -q https://github.com/godotengine/godot/releases/download/4.0.3-stable/Godot_v4.0.3-stable_linux.x86_64.zip
        unzip -q Godot_v4.0.3-stable_linux.x86_64.zip
        chmod +x Godot_v4.0.3-stable_linux.x86_64
        sudo mv Godot_v4.0.3-stable_linux.x86_64 /usr/local/bin/godot
    - name: Build APK
      run: |
        cd game
        godot --headless --export-release Android AI_Village_Life.apk
        ls -la
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: APK
        path: game/AI_Village_Life.apk
