name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Bisa trigger manual

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 
      
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Download Godot 4.0.3
      run: |
        wget https://github.com/godotengine/godot/releases/download/4.0.3-stable/Godot_v4.0.3-stable_linux.x86_64.zip
        unzip Godot_v4.0.3-stable_linux.x86_64.zip
        chmod +x Godot_v4.0.3-stable_linux.x86_64
        sudo mv Godot_v4.0.3-stable_linux.x86_64 /usr/local/bin/godot
        
    - name: Setup Export Templates
      run: |
        mkdir -p ~/.local/share/godot/export_templates
        wget https://github.com/godotengine/godot/releases/download/4.0.3-stable/Godot_v4.0.3-stable_export_templates.tpz
        unzip Godot_v4.0.3-stable_export_templates.tpz -d ~/.local/share/godot/export_templates/
        
    - name: Create Android Keystore
      run: |
        keytool -genkeypair \
          -v \
          -keystore android.keystore \
          -alias android \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass android \
          -keypass android \
          -dname "CN=AI Village Life, OU=Game, O=AI Village, L=Jakarta, ST=Jakarta, C=ID"
          
    - name: Build Android APK
      run: |
        cd game
        mkdir -p build
        godot --headless --export-release "Android" build/AI_Village_Life.apk
        
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4 
      with:
        name: AI-Village-Life-APK
        path: game/build/AI_Village_Life.apk
        retention-days: 30
