name: Build APK
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: firebelley/godot-export@v2.4.0
        with:
          godot_version: '4.0.3'
          export_preset: 'Android'
          relative_project_path: 'game'
      - uses: actions/upload-artifact@v4
        with:
          name: Game-APK
          path: game/build/
