name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Godot
      run: |
        wget -q https://github.com/godotengine/godot/releases/download/4.0.3-stable/Godot_v4.0.3-stable_linux.x86_64.zip
        unzip -q Godot_v4.0.3-stable_linux.x86_64.zip
        chmod +x Godot_v4.0.3-stable_linux.x86_64
        sudo mv Godot_v4.0.3-stable_linux.x86_64 /usr/local/bin/godot
        godot --version
        
    - name: Setup export templates
      run: |
        mkdir -p ~/.local/share/godot/export_templates
        wget -q https://github.com/godotengine/godot/releases/download/4.0.3-stable/Godot_v4.0.3-stable_export_templates.tpz
        unzip -q Godot_v4.0.3-stable_export_templates.tpz -d ~/.local/share/godot/export_templates/
        
    - name: Verify project structure
      run: |
        echo "=== Project Structure ==="
        ls -la game/
        echo "=== Source Files ==="
        ls -la game/src/ || echo "No src folder"
        echo "=== Project File ==="
        cat game/project.godot
        
    - name: Build APK
      run: |
        cd game
        mkdir -p build
        echo "🚀 Building APK..."
        godot --headless --export-release Android build/AI_Village_Life.apk
        echo "Build process completed!"
        
    - name: Check APK result
      run: |
        echo "=== Build Results ==="
        ls -la game/build/ || echo "No build folder"
        if [ -f "game/build/AI_Village_Life.apk" ]; then
          echo "🎉 SUCCESS: APK file found!"
          ls -lh game/build/AI_Village_Life.apk
        else
          echo "❌ FAILED: No APK file created"
          echo "Trying to find any APK files..."
          find . -name "*.apk" -type f
          exit 1
        fi
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: AI-Village-Life-APK
        path: game/build/AI_Village_Life.apk
        retention-days: 30
