name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Debug - List project structure
      run: |
        echo "=== PROJECT STRUCTURE ==="
        find . -type f -name "*.gd" -o -name "*.godot" | head -20
        ls -la game/
        
    - name: Install Godot
      run: |
        wget -q https://github.com/godotengine/godot/releases/download/4.0.3-stable/Godot_v4.0.3-stable_linux.x86_64.zip
        unzip -q Godot_v4.0.3-stable_linux.x86_64.zip
        chmod +x Godot_v4.0.3-stable_linux.x86_64
        sudo mv Godot_v4.0.3-stable_linux.x86_64 /usr/local/bin/godot
        
    - name: Try simple Godot test
      run: |
        cd game
        godot --headless --version
        echo "Godot installed successfully!"
        
    - name: Create minimal Main.gd if missing
      run: |
        if [ ! -f "game/src/Main.gd" ]; then
          echo "Creating minimal Main.gd..."
          mkdir -p game/src
          cat > game/src/Main.gd << 'EOF'
extends Node
func _ready():
    print("AI Village Life - Minimal Test Version")
EOF
        fi
        
    - name: Fix project.godot filename
      run: |
        cd game
        if [ -f "project.gdot" ]; then
          mv project.gdot project.godot
          echo "Fixed project.godot filename"
        fi
