name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Download Godot 4.0.3
      run: |
        wget https://github.com/godotengine/godot/releases/download/4.0.3-stable/Godot_v4.0.3-stable_linux.x86_64.zip
        unzip Godot_v4.0.3-stable_linux.x86_64.zip
        chmod +x Godot_v4.0.3-stable_linux.x86_64
        sudo mv Godot_v4.0.3-stable_linux.x86_64 /usr/local/bin/godot
        
    - name: Setup Export Templates
      run: |
        mkdir -p ~/.local/share/godot/export_templates
        wget https://github.com/godotengine/godot/releases/download/4.0.3-stable/Godot_v4.0.3-stable_export_templates.tpz
        unzip Godot_v4.0.3-stable_export_templates.tpz -d ~/.local/share/godot/export_templates/
        
    - name: Debug - List files before build
      run: |
        echo "=== STRUKTUR FILE ==="
        find . -name "*.gd" -o -name "*.godot" | head -20
        echo "=== PROJECT.GODOT ==="
        cat game/project.godot || echo "File project.godot tidak ditemukan!"
        
    - name: Build Android APK
      run: |
        cd game
        echo "=== MEMBUILD APK ==="
        godot --headless --export-release "Android" build/AI_Village_Life.apk
        echo "Build selesai dengan exit code: $?"
        
    - name: Debug - Check build results
      run: |
        echo "=== FILE SETELAH BUILD ==="
        find . -name "*.apk" -type f
        echo "=== ISI FOLDER BUILD ==="
        ls -la game/build/ || echo "Folder build tidak ada!"
        echo "=== ISI FOLDER GAME ==="
        ls -la game/
        
    - name: Upload APK Artifact
      if: success() && hash('game/build/AI_Village_Life.apk')
      uses: actions/upload-artifact@v4
      with:
        name: AI-Village-Life-APK
        path: game/build/AI_Village_Life.apk
        retention-days: 30
